### ISSUE TITLE
Quaternion types are missing

### ISSUE THREAD

**Issue by raphi-sama** [three-types/three-ts-types#113]
-   `three`: 0.131.3
-   `node`: 10.16.3
-   `npm` (or `yarn`) version: 1.19.0

### Problem description:

The new Quaternion.d.ts is missing at least some important types

The latest version of `@types/three`, the following static method typing is **missing** from [Quaternion.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/57445eb2857e4a96af84e75de9bae176753f003a/types/three/src/math/Quaternion.d.ts):

```
	static slerp(
		qa: Quaternion,
		qb: Quaternion,
		qm: Quaternion,
		t: number
	): Quaternion;
```

 even though this is a static function in [Quaternion.js (r130)](https://github.com/mrdoob/three.js/blob/d0340e3a147e290fa86d14bc3ed97d8e1c20602e/src/math/Quaternion.js#L14)

### Suggested solution:

Copy over the types

**Comment by joshuaellis** [comment]
A PR is welcome, otherwise I'll try do this when I find to make the r131 version of the type library.
