### ISSUE TITLE
Missing types in r167

### ISSUE THREAD

**Issue by haakonflatval-cognite** [three-types/three-ts-types#1142]
Hi! When upgrading to r167, I notice that a few types are no longer present. In my case all of the following types were missing:
```
import {
  type WebGLCapabilities,
  type WebGLColorBuffer,
  type WebGLDepthBuffer,
  type WebGLExtensions,
  type WebGLInfo,
  type WebGLRenderLists,
  type WebGLState,
  type WebGLStencilBuffer
} from 'three';
```

I suspect this happened in PR #1079. 

Could you confirm whether this is indeed a bug, or if I'm missing something?

Thanks

**Comment by Methuselah96** [comment]
Yes, it's a bug, I'll create a PR to fix it soon
