### ISSUE TITLE
Issue: should we model members declared in src but not mentioned in docs

### ISSUE THREAD

**Issue by ycw** [three-types/three-ts-types#115]
### What is your question:

e.g. Some ctor parameters ( eg `thickness`, `thicknessMap`, ... ) are potentially missing in MeshPhysicalMaterial.d.ts 

they;re declared in src: https://github.com/mrdoob/three.js/blob/r131/src/materials/MeshPhysicalMaterial.js#L77 
but not listed in docs : https://threejs.org/docs/index.html?q=physical#api/en/materials/MeshPhysicalMaterial

**Comment by joshuaellis** [comment]
You're welcome to submit a PR for this if the property exists on the class and hasn't been added to the types! 👍🏼

**Comment by joshuaellis** [comment]
Reviewing this issue. We do typically try to do this and sort of try to include the private members using the `private` type. But if in doubt, we include it in the type files, however, due to the sheer number of files we're not going to be retrofitting the codebase to resolve the issue.
