### ISSUE TITLE
BufferGeometryUtils is now imported as `import * as BufferGeometryUtils from ...`

### ISSUE THREAD

**Issue by grndctrl** [three-types/three-ts-types#117]
### Describe the bug

With the release of 0.132.x the type definitions for BufferGeometryUtils appear to be broken.
I think the @types/three need to be updated accordingly. See:
https://github.com/mrdoob/three.js/wiki/Migration-Guide

### To Reproduce
Import as suggested in the migration article:
`import * as BufferGeometryUtils from "three/examples/jsm/utils/BufferGeometryUtils";`

Use any of the utilities, i.e. `BufferGeometryUtils.mergeVertices(geometry)`

It break on the error:
`Property 'mergeVertices' does not exist on type 'typeof ...`

### Live example

https://codesandbox.io/s/elated-rhodes-bifl9?file=/src/index.ts

### Versions

three: 0.132.2
@types/three: 0.131.0

**Comment by Methuselah96** [comment]
Resolved by https://github.com/three-types/three-ts-types/pull/118.
