### ISSUE TITLE
New `format` property was added to the `Material` in r132

### ISSUE THREAD

**Issue by benpigchu** [three-types/three-ts-types#121]
-   `three` version: r132
-   `node` version: v16.6.2
-   `yarn` version: 3.0.1

### Problem description:

mrdoob/three.js#22428 adds a new `format` property on the `Material`, see mrdoob/three.js#22458

### Relevant code:

```ts
obj.material.format = THREE.RGBAFormat;
```

### Suggested solution:

Add a `format:PixelFormat` to `Material` and `MaterialParameters `

**Comment by joshuaellis** [comment]
There is no r132 release as of yet. All the issues we believe need addressing are listed here – https://github.com/three-types/three-ts-types/issues/114 Feel free to create PR contributions for this and we can as a community release r132.
