### ISSUE TITLE
Empty objects in event map leads to ESLint errors

### ISSUE THREAD

**Issue by sguimmara** [three-types/three-ts-types#1288]
Consider the following event map:

```ts
interface MyCustomEventMap {
   foo: {};
}
```

Here, the `foo` event does not take any value. However, ESLint complains that 

> [!WARNING]  
> ```ts
> The `{}` ("empty object") type allows any non-nullish value, including literals like `0` and `""`.
> - If that's what you want, disable this lint rule with an inline comment or configure the 'allowObjectTypes' rule option.
> - If you want a type meaning "any object", you probably want `object` instead.
>  - If you want a type meaning "any value", you probably want `unknown` instead.
>  ```

And indeed, what I really want is "the empty object". TypeScript says that an empty object is `Record<string, never>`.

However, this then fails to typecheck because this object can no longer be combined with the `BaseEvent` of the `EventDispatcher`:

```ts
this.dispatchEvent({ type: 'foo' })
```

Raises the following error:

> [!WARNING]  
>```ts
> Argument of type '{ type: "foo"; }' is not assignable to parameter of type 'BaseEvent<"foo"> & Record<string, never>'.
>  Type '{ type: "foo"; }' is not assignable to type 'Record<string, never>'.
>    Property 'type' is incompatible with index signature.
>      Type '"foo"' is not assignable to type 'never'.
>```

I'm note sure what is the best course of action here.

**Comment by Methuselah96** [comment]
That ESLint rule is a little iffy in my opinion because it's common practice to use `{}` in type parameter positions where it doesn't matter that it includes literals. However, I think you can use either `object` or `unknown` as suggested in the original error message.

**Comment by sguimmara** [comment]
Thanks, I opted for `unknown` :)
