### ISSUE TITLE
Repository description

### ISSUE THREAD

**Issue by satelllte** [three-types/three-ts-types#1292]
Hi 👋🏻 
This might be a better description for this repository:

```diff
- TS type library for the popular webgl library threejs
+ TypeScript types for the popular 3D library Three.js
```

because Three.js isn't only WebGL-based, but it also has other renderers and it's more like "the most popular 3D library on the web" kind of thing

**Comment by Methuselah96** [comment]
👍 Updated. I suspect that the original description was based on three.js's description (i.e., that three.js's description used to just mention WebGL).
