### ISSUE TITLE
0.132.1 serves type definition of r133 by mistake?

### ISSUE THREAD

**Issue by 0b5vr** [three-types/three-ts-types#136]
-   `three` version: Boundary between r132 / r133
-   `node` version: ----
-   `npm` (or `yarn`) version: ----

### Problem description:

`@types/three#0.132.1` .
I just noticed that the type signature of `GLTFReference` in `GLTFLoader.d.ts` has been changed to `r133` 's one by mistake.

You might possibly have been used `dev` instead of `master` when you publish `0.132.1` ...?

### Relevant code:

`GLTFLoader.d.ts @ @types/three#0.132.0`: 
https://unpkg.com/browse/@types/three@0.132.0/examples/jsm/loaders/GLTFLoader.d.ts

`GLTFLoader.d.ts @ @types/three#0.132.1`: 
https://unpkg.com/browse/@types/three@0.132.1/examples/jsm/loaders/GLTFLoader.d.ts

The PR introduces the change ( `three` ): 
https://github.com/mrdoob/three.js/pull/21737

**Comment by 0b5vr** [comment]
I can't find when you have changed this definition in this repository...? It might be your local change

**Comment by Methuselah96** [comment]
Yeah, unfortunately sometimes some changes sneak in through DefinitelyTyped and are merged in by DT maintainers without waiting for our review. In this case https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55977 was the PR that snuck through.

**Comment by joshuaellis** [comment]
I've left a comment addressing this issue. Thanks for raising it @0b5vr.

**Comment by 0b5vr** [comment]
Ouchhh, I got the story. Thank you for addressing this, Close this issue once it is settled on DT side.

**Comment by joshuaellis** [comment]
They've just reverted that PR, r132.1 will still be broken, but r132.2 will work I believe.
