### ISSUE TITLE
Add Nodes

### ISSUE THREAD

**Issue by joshuaellis** [three-types/three-ts-types#137]
### Describe the feature you'd like:

https://github.com/three-types/three-ts-types/issues/129#issuecomment-932963150

TLDR; Nodes is missing in `three/examples/jsm/renderers/nodes` and has partial support in `three/examples/jsm/nodes`. Would really appreciate some help getting these in order 🙏🏼

**Comment by ycw** [comment]
@joshuaellis #115 related?
