### ISSUE TITLE
OrbitalControls -> Allow mouse control to be null 

### ISSUE THREAD

**Issue by alexpineda** [three-types/three-ts-types#144]
![image](https://user-images.githubusercontent.com/586716/138660499-5bb20fa7-afad-40db-a70a-b19e582907b7.png)
When using TypeScript the mouse control is not allowed to be nullable when in fact I wish to not have any control for that mouse button.

The typescript definition should allow MOUSE | undefined | null

**Comment by joshuaellis** [comment]
Is this allowed in three.js?

**Comment by alexpineda** [comment]
Yes.

https://github.com/mrdoob/three.js/blob/dev/examples/jsm/controls/OrbitControls.js#L953

It sets state to none if the switch case does not match any MOUSE enum.

**Comment by Lutymane** [comment]
Maybe better do?

`mouseButtons: Partial<{ LEFT: MOUSE; MIDDLE: MOUSE; RIGHT: MOUSE }>;`
