### ISSUE TITLE
extending  THREE.Curve

### ISSUE THREAD

**Issue by sancelot** [three-types/three-ts-types#146]
Hi, my question may be silly , but why I have this mistake, when I want to extend Curve ?

class Polyline3D extends THREE.Curve {
=> Generic type 'Curve' requires 1 type argument(s).ts(2314)

**Comment by joshuaellis** [comment]
Because the points of a `Curve` can be in different spaces. i.e you may want to use a `Vector3` to make your curve like the class `CubicBezierCurve3`. 

So _assuming_ you want to create a curve with 3D space (x,y,z) you would do something like this:

```js
class Polyline3D extends THREE.Curve<THREE.Vector3> {
  // class information
}
```
