### ISSUE TITLE
three/examples/jsm/utils/SceneUtils does not work.

### ISSUE THREAD

**Issue by Kyohei-Ishihara** [three-types/three-ts-types#153]
SceneUtils is defined as namespace in SceneUtils.d.ts.
SceneUtils.js does not support it

**Comment by joshuaellis** [comment]
Please provide more information with an perhaps a codesandbox example of the issue so we can correctly look into it.

**Comment by Kyohei-Ishihara** [comment]
```
import { SceneUtils } from "three/examples/jsm/utils/SceneUtils";

const mesh = SceneUtils.createMultiMaterialObject(geoms[i], materials);
```

This code can be compiled, but it doesn't work. Error is that SceneUtils not found in three/examples/jsm/utils/SceneUtils (on Terminal). createMultiMaterialObject is not a function(on Console).
The reason is as follows.
- createMultiMaterialObject is defined into namespace(SceneUtils) in SceneUtils.d.ts.
- But createMultiMaterialObject  is not defined into namespace(SceneUtils) on SceneUtils.js.

**Comment by b1616** [comment]
I believe it may have resulted from this change https://github.com/mrdoob/three.js/pull/22284 which does as @Kyohei-Ishihara described, changing a handful of util functions that were previously defined in classes to being plain functions to facilitate tree shaking.
