### ISSUE TITLE
GLTFExporter - Add onError parameter to .parse()

### ISSUE THREAD

**Issue by ktedore** [three-types/three-ts-types#170]
three.js r135
GLTFExporter - Add onError parameter to .parse()

https://github.com/three-types/three-ts-types/blob/412f6bc6adc52b151eb5f29f3e57de6a0aff53ef/types/three/examples/jsm/exporters/GLTFExporter.d.ts#L18

**Comment by 0b5vr** [comment]
Agreed. I will review the interface of `GLTFExporter`.

https://github.com/mrdoob/three.js/blob/c7d06c02e302ab9c20fe8b33eade4b61c6712654/examples/jsm/exporters/GLTFExporter.js#L100
