### ISSUE TITLE
Issue: Some Declarations Might be `@deprecated`

### ISSUE THREAD

**Issue by ycw** [three-types/three-ts-types#174]
Please help checking if the following declarations did exist before (=adds `@deprecated`), 

or they're declared wrongly in the first place (=removes declarations)

### AnimationUtils ([src](https://github.com/mrdoob/three.js/blob/master/src/animation/AnimationUtils.js#L45))
- [x] getKeyFrameOrder (wrongly typed in the first place https://github.com/mrdoob/three.js/commit/2e5d9ef6b3fd42ca5b5f8074720b11c2ce0519ef, should be `getKeyframeOrder`)

### BufferGeometry  ([src](https://github.com/mrdoob/three.js/blob/master/src/core/BufferGeometry.js))
- [x] MaxIndex (removed https://github.com/mrdoob/three.js/commit/4f98376fb91daaa77cf80c07e26aa33e1f56a6ec)

### InstancedBufferGeometry ([src](https://github.com/mrdoob/three.js/blob/master/src/core/InstancedBufferGeometry.js))
- [x] groups (removed https://github.com/mrdoob/three.js/commit/af197833fe3a4998ed46871ed632bc75b8505c8f)
- [x] addGroup (removed https://github.com/mrdoob/three.js/commit/af197833fe3a4998ed46871ed632bc75b8505c8f)

### Uniform ([src](https://github.com/mrdoob/three.js/blob/master/src/core/Uniform.js))
- [x] onUpdateCallback (removed https://github.com/mrdoob/three.js/commit/65b8e841fca9d00d38328ccf5922c20cdb179a01)

### Scene ([src](https://github.com/mrdoob/three.js/blob/master/src/scenes/Scene.js))
- [x] onBeforeRender (inherit)
- [x] onAfterRender (inherit)

### Plane ([src](https://github.com/mrdoob/three.js/blob/master/src/math/Plane.js))
- [x] orthoPoint (removed since https://github.com/mrdoob/three.js/commit/2e013698106dadf86c0465918f12307cae07ce05)

### DataTexture ([src](https://github.com/mrdoob/three.js/blob/master/src/textures/DataTexture.js))

- [x] format (override; should keep)

### WebGLRenderTarget ([src](https://github.com/mrdoob/three.js/blob/master/src/renderers/WebGLRenderTarget.js))

- [x] uuid (removed https://github.com/mrdoob/three.js/commit/01cae4ee609016d45e2842595502fa28331fd5d0)

**Comment by joshuaellis** [comment]
Thanks @ycw, 

if you do spot issues like this then it's helpful to just make PRs instead to resolve them!

In reference to your Math/Euler pull out, thats actually on the dev branch and we're not working on implementing new types until closer to the time.

**Comment by ycw** [comment]
@joshuaellis it's something I would expect the community to contribute to 😃 

could you reopen it.

**Comment by joshuaellis** [comment]
Can you first edit the comment (i've made some stylistic changes to help readability) to include references to what you're talking about. I think this must be a requirement if we're going to keep a list like this.

**Comment by ycw** [comment]
@joshuaellis edited, thanks!

**Comment by joshuaellis** [comment]
> @joshuaellis edited, thanks!

Do you have links to the THREE source code to add to these?

**Comment by ycw** [comment]
@joshuaellis added links to src (r137)

**Comment by ycw** [comment]
@joshuaellis updated src links to use `master`
