### ISSUE TITLE
WebGLRenderer.getContext() wrong returned type

### ISSUE THREAD

**Issue by hschwane** [three-types/three-ts-types#182]
-   `three` version: 0.137.5
-   `node` version: 14.19.0
-   `npm` version: 6.14.16

### Problem description:
`WebGLRenderer.getContext()` has a return type of `WebGLRenderingContext` but in reality it returns a `WebGL2RenderingContext` on most systems. See mrdoob/three.js#23555

### Suggested solution:
The typescript return type of `WebGLRenderer.getContext()` should be `WebGLRenderingContext | WebGL2RenderingContext`.

**Comment by joshuaellis** [comment]
this will be released in r139
