### ISSUE TITLE
Remove OrbitControls.enableKeys

### ISSUE THREAD

**Issue by 0b5vr** [three-types/three-ts-types#189]
-   `three` version: r137

### Problem description:

`OrbitControls.enableKeys` seems to be removed since https://github.com/mrdoob/three.js/pull/21054 .

Related: https://github.com/mrdoob/three.js/pull/23472

### Suggested solution:

Simply removing the signature will resolve this.
I think I should take a look at the https://github.com/mrdoob/three.js/pull/21054 again

**Comment by joshuaellis** [comment]
This isn't in the types anymore.
