### ISSUE TITLE
missing TransformControlsGizmo and TransformControlsPlane from TransformControls.d.ts

### ISSUE THREAD

**Issue by mike-wood-dywidag** [three-types/three-ts-types#202]
-   `three` version: 0.134.0
-   `node` version: 16.13.0
-   `npm` (or `yarn`) version: 8.1.0

### Problem description:

The THREE js library is missing TransformControlsGizmo and TransformControlsPlane from [TransformControls.js](https://github.com/mrdoob/three.js/blob/4e97ffa91ae782b5fd4b12735f301740953f5abd/examples/jsm/controls/TransformControls.js) exports

### Suggested solution:

Implement type definitions for TransformControlsGizmo and TransformControlsPlane in [TransformControls.d.ts](https://github.com/three-types/three-ts-types/blob/master/types/three/examples/jsm/controls/TransformControls.d.ts) in line with package exports

**Comment by joshuaellis** [comment]
We typically don't update previous versions of the library as it doesn't conform to semantic versioning, it's more revision based. 

Is this still relevant in the latest version of three?

**Comment by mike-wood-dywidag** [comment]
Hi, Yes, 
The latest version (r139) of three does export both from TransformControls.js at line [1556](https://github.com/mrdoob/three.js/blob/r139/examples/jsm/controls/TransformControls.js#L1556)

**Comment by joshuaellis** [comment]
Will be resolved in `0.140.0`
