### ISSUE TITLE
Missing TextGeometry and Font

### ISSUE THREAD

**Issue by Fennec-hub** [three-types/three-ts-types#206]
- `three` version: 0.139.2
- `node` version: 14.19.1
- `npm` (or yarn) version: 1.22.18

### Problem description:

- Module '"three"' has no exported member 'Font'.
- Module '"three"' has no exported member 'TextGeometry'.

### Relevant code:

```ts
import { TextGeometry, Font } from "three";
```

### Suggested solution:

Works with previous versions, I had to fall back to `0.130` to get it work.

**Comment by joshuaellis** [comment]
It was removed in a previous version of three. They moved it to the examples folder.

**Comment by Fennec-hub** [comment]
Thanks for the clarification.
But it's confusing, cause `import { TextGeometry, Font } from "three"` return the right classes, probably temporary aliases till the breaking change ... imho the ts declarations should also follow the same aliases.

**Comment by Methuselah96** [comment]
Are you sure they return the right classes? From looking at the source code, it looks like they just return a class or function that calls `console.error` ([TextGeometry](https://github.com/mrdoob/three.js/blob/dev/src/Three.Legacy.js#L2067-L2076), [Font](https://github.com/mrdoob/three.js/blob/dev/src/Three.Legacy.js#L2084-L2088)), although I haven't actually tested it.

**Comment by Fennec-hub** [comment]
My bad, I feel really dumb right now, 

Old code (not that old), complex text handling class, got confused with all the versioning. I was using an older version of three.js `0.130` with a newer version of `@types/three`.

Should've double checked, sorry again for the disturbance.
