### ISSUE TITLE
Add WebGPU files

### ISSUE THREAD

**Issue by joshuaellis** [three-types/three-ts-types#21]
### Describe the feature you'd like:

One of the biggest pieces of `three` that unknowingly to me is missing, is the `webgpu` and `nodes` files missing from `examples/jsm/renderers`. I've had a go myself at piecing it together and I think it needs someone who really understands it to make it work properly without countless bugs.

I do know currently you need to add `@webgpu/types` to the project as `gpu` is not yet officially extended from `Navigator`. There's a branch already with some work if someone wants to pick it up – `r126-node-materiallight`, but anyone is welcome to start from scratch.

Of course, we're all here to support where we can, this isn't a lone effort and it'd be great to have this in the repo.

**Comment by CodyJasonBennett** [comment]
Following #240, should I give this a go?

**Comment by joshuaellis** [comment]
If you're interested, yes that would be great. Afaik we're still missing this.

**Comment by Methuselah96** [comment]
There's been a good deal of work towards typing the WebGPU files, but also a long way to go until this is fully supported. Closing this for now since basic support exists, but feel free to create follow-up issues for specific issues that need to be fixed.
