### ISSUE TITLE
Typescript error in drag files 

### ISSUE THREAD

**Issue by deep9888** [three-types/three-ts-types#233]
```js
const MANAGER = new THREE.LoadingManager();
function sceneCreator(url,rootPath,assetMap) {

    const baseURL = LoaderUtils.extractUrlBase(url);
    const blobURLs = [];
    return new Promise((resolve, reject)=>{
        MANAGER.setURLModifier((url,path)=>{
            const normalizedURL = rootPath + decodeURI(url)
            .replace(baseURL,'')
            .replace(/^(\.?\/)/, '');

            if(assetMap.has(normalizedURL)){
                const blob = assetMap.get(normalizedURL);
                const blobURL = URL.createObjectURL(blob);
                blobURLs.push(blobURL);
                return blobURL;
            }
            return (path || '') + url;
        });
        const loader = new GLTFLoader(MANAGER)
        .setCrossOrigin('anonymous');

        loader.load(url, (gltf)=>{
            const root = gltf.scene;
            console.log(root);
        })
    })
```

### function to create simple dropzone-

```js
const input1 = document.querySelector("#file-input");
const dropArea = document.querySelector('.wrap') as HTMLElement || null;
const dropArea1 = document.querySelector('#c') as HTMLElement || null;

function createDropzone(){
    const drpCntrl = new SimpleDropzone(dropArea,dropArea1,input1);
    drpCntrl.on('drop',({files})=> load(files));
}
function load(fileMap){
    let rootPath;
    let rootFile;
    Array.from(fileMap).forEach(([path,file])=>{
        console.log('gggg',file.name);
        
        if(file.name.match(/\.(gltf|glb)$/)){
            rootFile = file;
            rootPath = path.replace(file.name, '');
        }
    })
    console.log(rootFile,rootPath);
    
    view(rootFile, rootPath, fileMap);
 }

 function view(rootFile, rootPath, fileMap){
    const fileURL = typeof rootFile === 'string'
    ? rootFile
    : URL.createObjectURL(rootFile);
    sceneCreator(rootFile,rootPath,fileMap);
 }
```

### Below image it underlines url,path
![7](https://user-images.githubusercontent.com/103727216/175251020-adfcf4ae-3cf6-4256-8d3d-34b6cef247f1.JPG)

### Error - 

> (parameter) url: any
> 
> Parameter ‘url’ implicitly has an ‘any’ type, but a better type may be inferred from usage.ts(7044)
> 
> Argument of type ‘(url: any, path: any) => any’ is not assignable to parameter of type ‘(url: string) => string’.ts(2345)
> 
> (parameter) path: any
> 
> Parameter ‘path’ implicitly has an ‘any’ type, but a better type may be inferred from usage.ts(7044)
> 
> Argument of type ‘(url: any, path: any) => any’ is not assignable to parameter of type ‘(url: string) => string’.ts(2345)

**Comment by joshuaellis** [comment]
You haven't typed your `function sceneCreator(url,rootPath,assetMap)` so `url` the prop you've created will be "any" by default.

Have you tried typing the function correctly first and seeing if that solves your error?

**Comment by deep9888** [comment]
Actually, I am new to typescript  I don't know how to define type first can you guide me above is my whole code... where I need to define type?

**Comment by joshuaellis** [comment]
> Actually, I am new to typescript I don't know how to define type first can you guide me above is my whole code... where I need to define type?

if you are new to typescript i suggest you follow this guide: https://www.typescriptlang.org/docs/handbook/typescript-from-scratch.html and go from there.

**Comment by deep9888** [comment]
But where is the issue in above all is working fine as per requirement... I also console some values and it gives according to that but why it underline that url, path only?
