### ISSUE TITLE
Error: If 'tslint.json' is present, it should extend "dtslint/dt.json"

### ISSUE THREAD

**Issue by alexpineda** [three-types/three-ts-types#242]
When attempting to setup the code base for contributing I'm getting an error.

I fork the repo (master branch only), clone it, run `yarn install`, and without any modifications I run `yarn test three` . I tried `npm test three` and it's the same issue.

```
Error: If 'tslint.json' is present, it should extend "dtslint/dt.json"
    at D:\dev\three-ts-types\node_modules\dtslint\bin\lint.js:157:19
    at Generator.next (<anonymous>)
error Command failed with exit code 1.
```

**Comment by joshuaellis** [comment]
will be released in next version of `@types/three`
