### ISSUE TITLE
SelectionHelper DefinitelyTyped definition diverges from SelectionHelper.js defintion

### ISSUE THREAD

**Issue by cklogs** [three-types/three-ts-types#247]
-   `three` version:  `three@0.139.2`
-   `node` version: `v16.13.1`
-   `npm` version: `8.5.0`

### Problem description:

The SelectionHelper current typescript definition, [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/three/examples/jsm/interactive/SelectionHelper.d.ts) defines three constructor params, whereas the current SelectionHelper.js implementation defines two, [here](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/interactive/SelectionHelper.js).

This is resulting in runtime errors and unit test failures when using the SelectionHelper class.

**Comment by joshuaellis** [comment]
this will be released in the next version of `@types/three`
