### ISSUE TITLE
Missing definition for THREE.ColorManagement.legacyMode

### ISSUE THREAD

**Issue by fulopkovacs** [three-types/three-ts-types#250]
-   `three` version: 0.143.0
-   `node` version: v18.7.0
-   `npm` (or `yarn`) version: 1.22.10 (yarn)

### Problem description:

I  have run into a few issues regarding the `ColorManagement` module:
- `ColorManagement` has a `legacyMode` property that is missing from the type definitions. Here's the property in the latest release of `three` (`three@0.143.0`): [link](https://github.com/mrdoob/three.js/blob/e22cb060cc91283d250e704f886528e1be593f45/src/math/ColorManagement.js#L24).
- `ColorManagement` is not exported properly. See how it's exported in  [`threejs`](https://github.com/mrdoob/three.js/blob/e22cb060cc91283d250e704f886528e1be593f45/src/Three.js#L131), but not in [`@types/three`](https://github.com/three-types/three-ts-types/blob/7d43269b9e7c482bed5d2a0f0e16b5c00ab70a8d/types/three/src/Three.d.ts#L135).

I'd be happy to make a PR if that helps. :relaxed: 

### Relevant code:j

```ts
import * as THREE from 'three';
// The following lines result in type errors, but they
// don't throw any errors when they are actually executed
THREE.ColorManagement;
THREE.ColorManagement.legacyMode;
```

### Suggested solution:

I'd love to add the missing type definitions myself in a PR, if you're okay with that. :relaxed:

**Comment by joshuaellis** [comment]
> I'd love to add the missing type definitions myself in a PR, if you're okay with that. ☺️

Sure feel free!
