### ISSUE TITLE
Missing 'fog' value for ShaderMaterial

### ISSUE THREAD

**Issue by zwubs** [three-types/three-ts-types#253]
-   `three` version: 0.143.0
-   `node` version: 16.13.2
-   `npm` (or `yarn`) version: 8.3.1

### Problem description:

When using the ShaderMaterial type, an implementation for the 'fog' boolean isn't within the ShaderMaterialParameters. As well, based on the implementation of the ShaderMaterial, it may be worth looking into if some other values should be considered.

### Relevant code:

```ts
export interface ShaderMaterialParameters extends MaterialParameters {
    uniforms?: { [uniform: string]: IUniform } | undefined;
    vertexShader?: string | undefined;
    fragmentShader?: string | undefined;
    linewidth?: number | undefined;
    wireframe?: boolean | undefined;
    wireframeLinewidth?: number | undefined;
    lights?: boolean | undefined;
    clipping?: boolean | undefined;

    extensions?:
        | {
              derivatives?: boolean | undefined;
              fragDepth?: boolean | undefined;
              drawBuffers?: boolean | undefined;
              shaderTextureLOD?: boolean | undefined;
          }
        | undefined;
    glslVersion?: GLSLVersion | undefined;
}
```

### Suggested solution:

My suggested solution is to add the 'fog' variable to these options. It also may be worth creating another issue/PR to discuss other values of ShaderMaterialParameters.

```ts
    fog?: boolean | undefined;
```

**Comment by joshuaellis** [comment]
Can you point to the `three.js` code that shows fog should be part of the parameters? Just so we can be sure this is representative of the class.

**Comment by zwubs** [comment]
Definitely!
```ts

	setValues( values ) {

		if ( values === undefined ) return;

		for ( const key in values ) {

			const newValue = values[ key ];

			if ( newValue === undefined ) {

				console.warn( 'THREE.Material: \'' + key + '\' parameter is undefined.' );
				continue;

			}

			const currentValue = this[ key ];

			if ( currentValue === undefined ) {

				console.warn( 'THREE.' + this.type + ': \'' + key + '\' is not a property of this material.' );
				continue;

			}

			if ( currentValue && currentValue.isColor ) {

				currentValue.set( newValue );

			} else if ( ( currentValue && currentValue.isVector3 ) && ( newValue && newValue.isVector3 ) ) {

				currentValue.copy( newValue );

			} else {

				this[ key ] = newValue;

			}

		}

	}

```

ShaderMaterial (and others) defer to this function on the Material class. This implementation means that you can overwrite any value of the class, even those you maybe shouldn't. But 'fog' would be included based on this logic.

**Comment by joshuaellis** [comment]
This will be released in the next version of `@types/three`
