### ISSUE TITLE
jsdoc in three

### ISSUE THREAD

**Issue by alexpineda** [three-types/three-ts-types#277]
Hey just wondering why jsdoc isn't used in three.js to help generate the types? Is this something that has been brought up before?

**Comment by CodyJasonBennett** [comment]
Yes, I brought this up as an alternative to wholly deleting types from the repo but they were adamant on relegating the burden elsewhere.

**Comment by 0b5vr** [comment]
I sometimes do that when I contribute to this repo.

https://github.com/three-types/three-ts-types/commit/a7499f6047d9b762a1772c6783e9e36cf9291c34

It surely requires a massive workload to do that manually 😅

**Comment by joshuaellis** [comment]
This is a huge undertaking more so than handling updating the types every month which currently I'm struggling to find a real capacity for.

So in short, the reason is workload.

**Comment by 0b5vr** [comment]
closing for now. I will try to put jsdoc as much as possible since I know it's convenient to have!
