### ISSUE TITLE
I think its too bad to remove the *.d.ts from three.js

### ISSUE THREAD

**Issue by beginor** [three-types/three-ts-types#28]
I think its too bad to remove the `*.d.ts` from this repo, those files should be generated from source file, not be maintained manually.

Typescript does not only work with ts files, but alwo can works with js files, please refer to this post : [TypeScript without TypeScript -- JSDoc superpowers](https://fettblog.eu/typescript-jsdoc-superpowers/)

If we add JSDoc to the source cold, we can generate excellent d.ts files with `tsc`.

**Comment by beginor** [comment]
There is a great [video](https://www.youtube.com/watch?v=YHvqbeh_n9U) on that. But there’s a lot, lot more to it than a couple of basic types in comments. Turns out working with JSDoc type gets you very far.

https://www.youtube.com/watch?v=YHvqbeh_n9U

**Comment by joshuaellis** [comment]
Did you look at the conversation about this in the `three` repo? The maintainers were adamant they didn't want to deal with any overhead, so here we are.

**Comment by CodyJasonBennett** [comment]
The PR is here: https://github.com/mrdoob/three.js/pull/21174.
