### ISSUE TITLE
WebGLMultipleRenderTargets extends wrong class

### ISSUE THREAD

**Issue by sanddyl** [three-types/three-ts-types#282]
[three-ts-types/types/three/src/renderers/WebGLMultipleRenderTargets.d.ts] should extends WebGLRenderTarget.
![image](https://user-images.githubusercontent.com/1051839/200758874-07456dd6-2143-45d4-bf1e-9b7abb7a6293.png)

**Comment by 0b5vr** [comment]
three.js side: https://github.com/mrdoob/three.js/blob/r146/src/renderers/WebGLMultipleRenderTargets.js
three-ts-types side: https://github.com/three-types/three-ts-types/blob/r146/types/three/src/renderers/WebGLMultipleRenderTargets.d.ts

Seeing the code in three-ts-types, it seems it used to have an issue with `.setTexture()` . https://github.com/mrdoob/three.js/issues/21930#issuecomment-1322068800 says that it's no longer a problem.

**Comment by imperiobadgo** [comment]
First of all, thank you everyone for the great work providing typescript definitions of three.js!

In my project I work with WebGLMultipleRenderTargets and as the next step I need the DepthTexture, which is stored in WebGLRenderTarget and can also be created via the options parameter of WebGLMultipleRenderTargets. I also noticed that WebGLMultipleRenderTargets does not inherit from the same as Three.js. This means that it is not possible to access the DepthTexture, even though I can see that it has been created when debugging. If anyone knows another way, I would be very grateful for that too.

`.setTexture()` is not available anymore on the three.js side...
