### ISSUE TITLE
Wrong type for `Data3DTexture.wrapR`

### ISSUE THREAD

**Issue by gegoggigog** [three-types/three-ts-types#316]
-   `three` version: master
-   `node` version: v19.3.0
-   `npm` (or `yarn`) version: 8.19.2

### Problem description:

Wrong type for `Data3DTexture.wrapR`

### Relevant code:
```ts
    /**
     * @default THREE.ClampToEdgeWrapping
     */
    wrapR: boolean;
```
### Suggested solution:

```ts
    /**
     * @default THREE.ClampToEdgeWrapping
     */
    wrapR: Wrapping;
```

Want me to make a pull request?

**Comment by 0b5vr** [comment]
https://github.com/three-types/three-ts-types/blob/master/types/three/src/textures/Data3DTexture.d.ts

Yep, it seems to be my mistake. Thank you!

@gegoggigog would you make a PR for us?

**Comment by gegoggigog** [comment]
Ok. Hope I followed all the steps. :)
https://github.com/three-types/three-ts-types/pull/320
