### ISSUE TITLE
three/addons alias

### ISSUE THREAD

**Issue by CodyJasonBennett** [three-types/three-ts-types#336]
### Describe the feature you'd like:

Since r144 (https://github.com/mrdoob/three.js/pull/23406), three.js supports a `three/addons` alias that would currently redirect to `three/examples/jsm`.

For instance, the following resolve to the same file:

```js
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js'
```

### Suggested implementation:

TypeScript doesn't recognize the above behavior since the alias is currently handled through `package.exports` and types only exist for `examples/jsm` on disk (this might be something to check in TypeScript upstream). We can implement this by copying `examples/jsm` to `addons` at build-time if there's no easy way to alias as a library.

You can work-around this in user-land with:

```json
{
  "compilerOptions": {
    "paths": {
      "three/addons/*": ["./node_modules/three/examples/jsm/*"]
    }
  }
}
```

**Comment by Methuselah96** [comment]
I think TypeScript will correctly perform the alias if we add the `exports` field to the `package.json` of `@types/three`. I've created #340 to do just that and it seems to work for me in my local testing (i.e., TypeScript lets me import `three/addons/controls/OrbitControls.js`). I'm hoping DefinitelyTyped will preserve the field when publishing the types, but we might have to try it to find out.

**Comment by Methuselah96** [comment]
Did some testing, and this won't work until [we add file extensions to imports](https://github.com/three-types/three-ts-types/pull/353), which is waiting on DefinitelyTyped to support imports with file extensions without having to add them to `OTHER_FILES`.
