### ISSUE TITLE
[RFC] Testing strategy

### ISSUE THREAD

**Issue by Methuselah96** [three-types/three-ts-types#365]
After thinking about https://github.com/three-types/three-ts-types/issues/326 some more, I think it would make sense to organize our tests a little more clearly.

I'm thinking we should have two categories of tests: unit type tests and integration type tests. The unit type tests would be more granular and would just be calling functions and making sure the return type is correct, etc. The integration tests would be full examples, similar to the kinds of tests we have now (taken from `three.js/examples/*.html`, but could also come from somewhere else).

Based on that distinction, I propose we establish a folder structure that makes it clear where to put tests. My current proposal is:

- `test`
  - `integration`
    - `three-examples`
      - [three examples here]
    - [other integration tests?]
  - `unit`
    - `examples`
      - `jsm`
        - `animation`
          - `AnimationClipCreator.test.ts`
          - etc.
        - etc.
    - `src`
      - `animation`
        - `AnimationAction.test.ts`
        - etc.
      - etc.

I am also working on [a tool](https://github.com/Methuselah96/three-ts-examples) to help us keep the three-examples up-to-date automatically. Hopefully you'll see some PRs soon adding tests that are maintained by that tool.

**Comment by joshuaellis** [comment]
> I am also working on [a tool](https://github.com/Methuselah96/three-ts-examples) to help us keep the three-examples up-to-date automatically. Hopefully you'll see some PRs soon adding tests that are maintained by that tool.

This is very exciting to hear. 

Would `helper-viewHelper.ts` be considered a unit test? Just so I understand. Also cc @0b5vr would love to see your opinions here :)

**Comment by Methuselah96** [comment]
> Would `helper-viewHelper.ts` be considered a unit test?

That would be considered a unit test, since it's focused on testing just a single unit (i.e., `ViewHelper`) and contains more fine-grained type assertions.

**Comment by joshuaellis** [comment]
Great, glad we're on the same page 💪🏼

**Comment by Methuselah96** [comment]
If @0b5vr is good with these changes as well, I'll make a PR to update the test directory to match the new directory structure.

**Comment by 0b5vr** [comment]
@Methuselah96 Sorry for the late response but the proposal sounds good to me 🙌
