### ISSUE TITLE
EventDispatcher Typing is very limited.

### ISSUE THREAD

**Issue by rafaelsc** [three-types/three-ts-types#368]
### Problem description:

The current `EventDispatcher` typing is very limited, 

- A unusual way to define strong type events, very different from what other TS Typing projects use.
- When using strong-type events, there are not easy to extend the definition to add more events.
- There are no strong-type events that ThreeJS currently uses.
- Type for `event.target` is set to _any_ currently.
- Classes that are EventDispatcher needs to allow dispatch and listening to any custom event, even if we are using strong-type events.

### Suggested solution:

- Update the typing using the same pattern that TS uses for DOM events.
- Add strong-type events to all known Threejs events.
- Use _interfaces_ to alow an easy way to extend the current strong-type events definitions.

**Comment by Methuselah96** [comment]
Resolved by https://github.com/three-types/three-ts-types/pull/369.
