### ISSUE TITLE
 ColorSpace constant type definitions for r149 cause issues with auto-formatting tools

### ISSUE THREAD

**Issue by Oletus** [three-types/three-ts-types#386]
-   `three` version: r149
-   `node` version: 18.14.0
-   `npm` (or `yarn`) version: 9.3.1

### Problem description:

ColorSpace constant type definitions for r149 cause issues with auto-formatting tools.

### Relevant code:

r149 types have this code:

```ts
export type NoColorSpace = '';
export type SRGBColorSpace = 'srgb';
export type LinearSRGBColorSpace = 'srgb-linear';
```

This is causing problems since some auto-formatting tools don't recognize when these values are used, and automatically remove them from import statements even if they are in fact being used.

This has been already fixed to this in latest master:

```ts
export const NoColorSpace: '';
export const SRGBColorSpace: 'srgb';
export const LinearSRGBColorSpace: 'srgb-linear';
```

### Suggested solution:

Would it be possible to backport the fix to the r149 version of types?

**Comment by Methuselah96** [comment]
The [r150 types](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64877) are hopefully close to getting released which fixes this issue. Just to clarify, will you be unable to upgrade to `@types/three@0.150.0` once it is released, or are you just requesting a backport due to the r150 types not being released yet?

**Comment by Methuselah96** [comment]
We don't usually do backports (and honestly don't even know if we can once r150 is released), so just trying to understand the motivation for the request.

**Comment by Oletus** [comment]
We have some customizations to three.js, so upgrading it is always a fair amount of work. That's why it would be nice if fixes could be backported in some cases like this where it's having a real impact on workflows. But if doing backports is not possible, it's understandable.

**Comment by Oletus** [comment]
Should this just be closed in case the general policy is not to do backports?

**Comment by joshuaellis** [comment]
Yes, good point.
