### ISSUE TITLE
TS2339: Property 'array' does not exist on type 'BufferAttribute | InterleavedBufferAttribute | GLBufferAttribute'.

### ISSUE THREAD

**Issue by Sean-Bradley** [three-types/three-ts-types#389]
Since `@types/three@0.149` and `@types/three@0.150`

Sample code,
```
const numbers = somemesh.geometry.attributes.position.array
```

now causes error

```
TS2339: Property 'array' does not exist on type 'BufferAttribute | InterleavedBufferAttribute | GLBufferAttribute'.
  Property 'array' does not exist on type 'GLBufferAttribute'.
```

Two temporary fixes,
`npm install @types/three@0.148`
or
`const numbers = (somemesh.geometry.attributes.position as any).array`

In plain JavaScript (`three@0.150.1`), you can still reference a geometries `attributes.position.array` without issue.

At the time of writing this issue, `@types/three@0.150.1` did not yet exist.

**Comment by Methuselah96** [comment]
An attribute can be a `GLBufferAttribute` which does not have an `array` property (see https://github.com/three-types/three-ts-types/pull/314). For now you can either cast it if you know it's not a `GLBufferAttribute` or "use the boolean flags (`isBufferAttribute`, `isInterleavedBufferAttribute`, or `isGLBufferAttribute`) to discriminate between the different options."

**Comment by Methuselah96** [comment]
Something like https://github.com/three-types/three-ts-types/pull/241 could be a potential solution to resolving this friction.

**Comment by Sean-Bradley** [comment]
In versions @types/three@0.148.1 and earlier,
the type of 
`geometry.attributes.position.array;`
was automatically inferred to 
`ArrayLike<number>`

The type was auto inferred and it worked perfectly. It caused no friction if the development.
It works in JavaScript, so why is TypeScript now telling you "NO".

And official Threejs examples use `attributes.position.array`. I've also seen `attributes.color.array` and `attributes.normal.array`
See BufferGeometry example code here [https://threejs.org/docs/#manual/en/introduction/How-to-update-things](https://threejs.org/docs/#manual/en/introduction/How-to-update-things)

Casting position as `TypeArray` does not work
`(geometry.attributes.position as TypedArray).array;`
yields
`type TypeArray = /*unresolved*/`
![image](https://user-images.githubusercontent.com/6302260/228834403-217fa500-b9c6-4cc9-b4bb-ee0d49898a69.png)



The only option that I can find that works, other than downgrading, is to cast `as any`,
![image](https://user-images.githubusercontent.com/6302260/228834271-5b93680a-1c7d-44a4-8488-1d91e7881822.png)



It was a nicer experience when it was just automatically inferred, and did not block you. Just like in this image.
![image](https://user-images.githubusercontent.com/6302260/228834824-0797c3bb-8857-4030-ae23-ac58757c81cd.png)

Now the type definition tells you, that you cannot do any of these any more.
```
attributes.position.array
attributes.color.array
attributes.normals.array
```

Yet, if you use plain old JavaScript, it works.

This restriction is new in 
@types/three@0.149.0
@types/three@0.150.0

----------

And this no longer works in TypeScript either. See `getAttribute` : [THREEJS Attributes](https://threejs.org/docs/#api/en/core/BufferGeometry.attributes)
![image](https://user-images.githubusercontent.com/6302260/228839545-d193cc15-15cc-48ce-8086-78fefac9520b.png)

But it does in plain old JavaScript. 
It shows that there is an `array` property in there.
![image](https://user-images.githubusercontent.com/6302260/228840401-9a058292-6d99-4272-9682-61471d47dc21.png)

The type is auto inferred to something useable.

There is no need for the end user to correct the type definitions in order to be able to use them.

There have been some very restrictive decisions made recently that it make these type definitions no longer compatible with the official Threejs.

**Comment by Sean-Bradley** [comment]
Ok, so it works if you do something like this

```
// using @types/three@150.0
const line = new THREE.Line( geometry, material );
const positions = (line.geometry.attributes.position as THREE.BufferAttribute).array
```

There was much less friction when the type was auto inferred and you could just write

```
// using @types/three@148.1
const line = new THREE.Line( geometry, material );
const positions = line.geometry.attributes.position.array
```

Is it really necessary to now also enforce the `GLBufferAttribute` type?
along with `THREE.BufferAttribute | THREE.InterleavedBufferAttribute`
Are you sure?

**Comment by Methuselah96** [comment]
Yes, that is generally how I've worked around the issue so far.

I agree that the friction is undesirable since the vast majority of three.js code does not use `GLBufferAttribute`s, however on the other end, the types need to be able to support `GLBufferAttribute`s since they're a valid buffer attribute.

I'm looking into ways to reduce the friction as much as possible while still retaining support for `GLBufferAttribute`s.

**Comment by Methuselah96** [comment]
> Is it really necessary to now also enforce the GLBufferAttribute type?
along with THREE.BufferAttribute | THREE.InterleavedBufferAttribute
Are you sure?

Yes, we need to allow the use of `GLBufferAttribute`, since it's part of three.js. How to allow its use while preserving the ease of using `BufferAttribute | InterleavedBufferAttribute` takes a little more work, which I am exploring at the moment.

**Comment by Methuselah96** [comment]
Reopening this to track this issue. I started working on this last month but hit some issues. Digging back into it now.
