### ISSUE TITLE
Sprite should accept SpriteMaterial or ShaderMaterial

### ISSUE THREAD

**Issue by eekelof** [three-types/three-ts-types#402]
-   `three` version: 0.146.0

### Problem description:
Sprite currently gives an error if a ShaderMaterial is passed instead of a SpriteMaterial.

### Suggested solution:
Change the Sprite constructor to this:
```ts
constructor(material?: SpriteMaterial | ShaderMaterial);
```

#### Links to relevant files:
https://github.com/three-types/three-ts-types/blob/master/types/three/src/objects/Sprite.d.ts
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/three/src/objects/Sprite.d.ts

**Comment by Methuselah96** [comment]
I'm not sure that we want to do this. The [Sprite docs](https://threejs.org/docs/index.html?q=sprite#api/en/objects/Sprite) seem to define the type of the material as a `SpriteMaterial`. In addition, the `Sprite.raycast` references some properties of the `SpriteMaterial` that are not properties of a `ShaderMaterial` like `sizeAttenuation` ([here](https://github.com/mrdoob/three.js/blob/dev/src/objects/Sprite.js#L80)) and `rotation` ([here](https://github.com/mrdoob/three.js/blob/dev/src/objects/Sprite.js#L86)).

So it seems like passing a `ShaderMaterial` has some gotchas that might not be obvious. I lean toward thinking the types should remain the same and that those who know what they're doing can just cast the material in TypeScript.
