### ISSUE TITLE
Incorrect type definition for the setOpaqueSort / setTransparentSort

### ISSUE THREAD

**Issue by germanz** [three-types/three-ts-types#41]
-   `three` version: 126

### Problem description:

``setOpaqueSort`` and ``setTransparentSort`` method arguments are documented as ``() => void`` thus passing a custom comparator in Typescript codebase leads to an error.

Here are the Type declarations:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/three/src/renderers/WebGLRenderer.d.ts#L289
https://github.com/three-types/three-ts-types/blob/master/types/three/src/renderers/WebGLRenderer.d.ts#L289
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/three/src/renderers/webgl/WebGLRenderLists.d.ts#L55

### Relevant code:

```ts
const painterSort = (a: Object, b: Object): number => { 
  return 0;
};
let renderer.setOpaqueSort(painterSort);
```

### Suggested solution:

``setOpaqueSort`` and ``setTransparentSort``method argument types should be documented as:

```(a: any, b: any) => number ```

The same goes for the ``sort`` method of the **WebGLRenderLists**.

**Comment by joshuaellis** [comment]
Hi @germanz, if you'd like to submit a PR to fix this, that would be fantastic. This being such a large repository we rely on contributors!
