### ISSUE TITLE
Build steps for repo

### ISSUE THREAD

**Issue by UncleFirefox** [three-types/three-ts-types#452]
### What is your question:
Hi, I'd like to fork this repo to support a custom THREE.js I have. Looked for a build step that simulates what you package up in npm releases but haven't found any, is there anything special I need to take into account?

**Comment by joshuaellis** [comment]
This repo goes through `DefinitelyTyped`, so the build pipeline is managed by them.

**Comment by Methuselah96** [comment]
Let us know if you have any further questions.
