### ISSUE TITLE
[infrastructure] automate this repo to the DT repo

### ISSUE THREAD

**Issue by joshuaellis** [three-types/three-ts-types#5]
It'd be good to get a pipeline working where the following steps occur:

1. We push to the `master` branch of the repo
2. Creates a PR into our DT fork with **only** the `types` folder
3. Once merged, creates a PR to the original DT fork

It'd be good to have this on Github, however looking at `p5-types` set up I think it'd have to be some kind of node job on your machine (I could be wrong).

**Comment by Methuselah96** [comment]
The only thing we have to consider is whether we're publishing more than once a month. If we are, we'll need two separate branches, one for the current release and one for the next release.

**Comment by joshuaellis** [comment]
Great point:

types repo could be: master = current release (125), dev = next release (126)
DT fork: we would only publish current release anyway so that can be just one branch. 

I think the best thing to do is a bot (working on atm, may take some time but the code will be in the org), using https://probot.github.io/

**Comment by Methuselah96** [comment]
Yeah, I'm good with that. And that we just merge `dev` into `master` when `dev` gets released?

**Comment by joshuaellis** [comment]
Yep I reckon so.

**Comment by joshuaellis** [comment]
Not sure we get enough traffic to warrant this for now.
