### ISSUE TITLE
Theee.d.ts imports .js files explicitly

### ISSUE THREAD

**Issue by OndrejSpanel** [three-types/three-ts-types#575]
A change in commit 952e7cc244436c1de7878c9e838f7293226935f4 (from #532) has changed all exports in Three.d.ts from extension-less to an explicit extension .js.

Before:

```
export * from './constants';
export * from './Three.Legacy';
```

```
export * from './constants.js';
export * from './Three.Legacy.js';
```

I am not sure I understand this correctly, perhaps I am wrong, but this looks like a mistake to me, as d.ts file should import d.ts files, not js files, as I think importing .js files causes d.ts file to be invisible and the type checking might not work properly.

**Comment by Methuselah96** [comment]
Thanks for the issue!

I think this is actually correct, based on [the docs on ESM](https://www.typescriptlang.org/docs/handbook/esm-node.html) and https://github.com/microsoft/TypeScript/issues/49083. You can also double-check this behavior by creating a TS project that has a `"type": "module"` in its `package.json` and uses `"module": "node16"`. If you emit declaration files, you'll see that the declaration files still use `.js` imports (the imports don't get rewritten).

Is this causing issues for you?

**Comment by OndrejSpanel** [comment]
I use a conversion tool which probably does not handle this as it should. Thanks for references, I will solve the issue on the tool side.
