### ISSUE TITLE
Consider removing all-contributors

### ISSUE THREAD

**Issue by Methuselah96** [three-types/three-ts-types#600]
In my experience, it actually ends up making it harder to contribute rather than easier. I've had a hard time getting it to work consistently on Windows and don't want to spend time looking into it. It's a good idea, but it seems like people can also look at the ["Contributors" view](https://github.com/three-types/three-ts-types/graphs/contributors) on GitHub. @joshuaellis Let me know if you have any thoughts.

**Comment by joshuaellis** [comment]
yeah, i think it was a nice idea, but it also create's unnecessary merge conflicts impacting negatively on the contributor experience – imo it can be ridden of 👍🏼
