### ISSUE TITLE
Cannot import from examples/jsm

### ISSUE THREAD

**Issue by levsa** [three-types/three-ts-types#626]
### What is your question:

I'm trying to import `WebGL` as follows:

```typescript
import * as THREE from 'three';   // works fine
import {WebGL} from 'three/examples/jsm/capabilities';  // Failed to resolve 'three/examples/jsm/capabilities' from '.src/main.ts'
```

But it fails. I wonder if I'm doing anything wrong, or does this not work with `@types/three`.

**Comment by Methuselah96** [comment]
Does this for you during runtime? It doesn't seem like it should.

I would try importing like this:

```ts
import WebGL from 'three/addons/capabilities/WebGL.js';
```

as shown [here](https://threejs.org/docs/index.html#manual/en/introduction/WebGL-compatibility-check).

**Comment by levsa** [comment]
> Does this for you during runtime? It doesn't seem like it should.
> 
> I would try importing like this:
> 
> ```ts
> import WebGL from 'three/addons/capabilities/WebGL.js';
> ```
> 
> as shown [here](https://threejs.org/docs/index.html#manual/en/introduction/WebGL-compatibility-check).

I got it working like this:

```
import WebGL from 'three/examples/jsm/capabilities/WebGL'
```

Thanks for your help!
