### ISSUE TITLE
Unify typeof .userData property

### ISSUE THREAD

**Issue by hanvit-eazel** [three-types/three-ts-types#656]
### Description

Issue submitted in three.js first
[link](https://github.com/mrdoob/three.js/issues/27070)
And also submitted in definitely typed at second
[link](https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/67213)

Here are the classes that currently use the userData property in three.js.
(captured from @types/three r155.1)

<img width="520" alt="hasUserData" src="https://github.com/mrdoob/three.js/assets/82128390/0bb2f1c6-a338-4e2c-bbe2-7b0b38957faf">

- Object3D
- BufferGeometry
- Material
- Texture
- (UserDataNode, GLTF)

But as you can see, Object3D, BufferGeometry and Material, Texture have different userData types.

This situation caused me the following type issue.

<img width="570" alt="error" src="https://github.com/mrdoob/three.js/assets/82128390/2e629873-132b-45aa-870e-94867dac5910">

```
type UserDataWrappedObject3D = Object3D & {
    userData: { myCustomValue: number }
}

type UserDataWrappedMaterial = Material & {
    userData: { myCustomValue: number }
}

let a: UserDataWrappedObject3D 
let b: UserDataWrappedMaterial 

a.userData.myCustomValue
b.userData.myCustomValue // error from userData inferred as any
```

### Solution

If we want to allow wrapping of userData in the above manner, I suggest replacing the userData type of Materials and Textures with Object3D or BufferGeometry's userData type.

```
// in Material class
...
userData: { [key: string]: any };
...
```

### Alternatives

Or we can apply `Record` type for userData as it commented in code.

**Comment by hanvit-eazel** [comment]
Additionally, overwrittening .data property of the Source class is not working correctly too.

This is solved by replacing `any` with `unknown`, I would suggest using `unknown` as normal lint rules.

```
let a: DataWrappedSource

type DataWrappedSource = Source & {
    data: HTMLImageElement // eg
}

a.data // data inferred as any
```

<img width="650" alt="problem" src="https://github.com/three-types/three-ts-types/assets/82128390/ef22497f-9764-49bc-98e7-1a4f75f919bc">

**Comment by Methuselah96** [comment]
> Additionally, overwrittening .data property of the Source class is not working correctly too.

This is a separate issue, if you could create a new issue for this so it's progress can be tracked separately, that would be appreciated.
