### ISSUE TITLE
has r127 been published to npm?

### ISSUE THREAD

**Issue by frading** [three-types/three-ts-types#67]
-   `three` version: 0.127.0
-   `node` version: 12.16.1
-   `npm` (or `yarn`) version: 1.22.4

### Problem description:

I'm in the process of upgrading an app from three 125 to 127. I've done the upgrade to 126 successfully, using the version 0.126.2 of @types/three. So thanks a ton for taking ownership of those types.
And to upgrade to three@0.127.0, I was expecting a similar version number for @types/three, but from what I see on https://www.npmjs.com/package/@types/three, 0.126.2 seems to be the latest published.

But then you seem to have released r127 https://github.com/three-types/three-ts-types/releases/tag/r127

Could it be that r127 has not yet been published to npm? Or I may be missing something obvious, so feel free to point me to the right direction if that's the case.

### Relevant code:

N/A

### Suggested solution:

N/A

**Comment by Methuselah96** [comment]
Not yet. It's waiting on a DefinitelyTyped maintainer to merge [this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52113).

**Comment by frading** [comment]
ah I see. I did not realise that was a necessary step. Sounds very good, thanks a lot for your quick reply.

**Comment by joshuaellis** [comment]
Its being published on DefinitelyTyped now 🎉

**Comment by frading** [comment]
Excellent, thanks a lot!
