### ISSUE TITLE
wrong Gamepad used in XRInputSource.Gamepad

### ISSUE THREAD

**Issue by sjpt** [three-types/three-ts-types#70]
-   `three` version: 127
-   `node` version: 6.14.5
-   `npm` (or `yarn`) version:

### Problem description:
The XRInputSource.gamepad has type Gamepad, which is defined as the generic lib.dom.d.ts Gamepad which is wrong (? the old nagivator.getamepad() gamepad?)

It should use an XRGamepad interface, something like
```
export interface XRGamepad {
    readonly id: string;
    readonly index: N;  // long
    readonly connected: boolean;
    readonly timestamp: DOMHighResTimeStamp;
    readonly mapping: GamepadMappingType;
    readonly axes: Float32Array;  // FrozenArray<double>;
    readonly buttons: GamepadButton[]; // FrozenArray<GamepadButton>;
}
```

### Suggested solution:

see XRGamepad definition above (not sure about FrozenArray)

**Comment by joshuaellis** [comment]
I have no experience in webXR, if you want a fix, I'd advise you to submit a PR 😄

**Comment by CodyJasonBennett** [comment]
Where are you getting XRGamepad from? The current implementation seems to be correct with [what Immersive Web has](https://immersive-web.github.io/webxr-gamepads-module/#xrinputsource-interface).

**Comment by sjpt** [comment]
Thanks for the response. XRGamepad was my name, as Gamepad is ambiguous.

There is a Gamepad interface defined in the XR spec, which I called XRGamepad and is defined following the link in your reference at https://w3c.github.io/gamepad/#dom-gamepad. This matches what I see during runtime in Chrome.

However, that (XR) Gamepad interface is not defined in WebXR.d.ts, but (at least in my VSCode typescript setup) falls through to the Gamepad definition in lib.dom.d.ts, which the the Gamepad interface of the Gamepad API (https://developer.mozilla.org/en-US/docs/Web/API/Gamepad), as returned by navigator.getGamepad().

As far as I can see, there is no type definition for the 'correct' XR Gamepad interface except in my code snippet above; and in the patched version on this machine which I could submit as a PR if that would help.

**Comment by sjpt** [comment]
It looks as if there is a similar _potential_ issue in the GamepadButton interface; but GamepadButton is the same in WebXR and Gamepad APIs. It might be cleaner to redefine it in WebXR.d.ts, to reflect the fact is is the version from the WebXR spec.

**Comment by joshuaellis** [comment]
isn't there a type library for `web/xr` we could/should be using here anyway? – https://github.com/three-types/three-ts-types/issues/31

**Comment by sjpt** [comment]
I've looked for one, because as you say most of it is not three.js specific
eg 'npm install @types/webxr' accesses one that is essentially the same including in the use of Gamepad ... not sure how the two relate, I thought they were the same.

Should I have put the issue on
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/webxr
and then you rely on that?

**Comment by joshuaellis** [comment]
Well we dont use that library atm, so updating the `@types/webxr` won't solve the issue at hand. But you could do both or even solve both  😛

**Comment by xinaesthete** [comment]
It sounds like it would make sense to change `@types/webxr` to have the appropriate interface, and `@types/three` to use that, once it's been appropriately updated.

**Comment by sjpt** [comment]
Given the ambiguity of Gamepad, do you think it more appropriate to name the XR version Gamepad and perpetuate potential confusion between the two, or to name it XRGamepad and thus deviate (in that type name only) from the XR spec?

It's clear the potential confusion is significant as both the implementations of the typescript interface made the same mistake.
(It would have been easier still if the XR spec had used the orginal Gamepad interface, but too late for that now ...)

**Comment by Methuselah96** [comment]
I think naming it `XRGamepad` is the way to go. I would need to doublecheck, but I believe there are other XR interface names that we've prepended XR to in order to disambiguate them.

**Comment by sjpt** [comment]
Most are sensibly prefixed XR in the XR spec. I haven't seen any that were not, but where you prepended XR. I'm not sure why Gamepad wasn't defined as XRGamepad in the spec.

**Comment by sjpt** [comment]
I've tried to do a pull request but it's failing on 'yarn run prettier:check'
I installed yarn and tried to run that locally to see what was wrong, but it just gave a huge list of files with [warn], and no indication about what it didn't like with the specific file WebXR.d.ts

changed file at
https://github.com/sjpt/three-ts-types/blob/master/types/three/src/renderers/webxr/WebXR.d.ts

**Comment by Methuselah96** [comment]
What happens when you run `yarn run prettier:write`?

**Comment by sjpt** [comment]
Thanks for the the suggestion. After quite a bit of confusion (on my part) with the way prettier works and squashing commits I have resubmitted a new pull request.
(Prettier didn't like two blanks between ; and //, and I didn't notice it had changed/corrected my local file without comment at some point)
