### ISSUE TITLE
Return `this` type instead of `Matrix4` for in-place mutations

### ISSUE THREAD

**Issue by TimJentzsch** [three-types/three-ts-types#704]
# Objective

I would like to create a subclass of `Matrix4` to add my own custom methods while maintaining type safety.
However, when using functions like `.multiply`, the subclass is "lost", because it returns type `Matrix4`.
In reality, `.multiply` is an in-place operation which returns `this`, so the subclass is preserved.

## Example

```ts
export class Matrix4Ext extends Matrix4 {
  extension(): this {
    // -- Do stuff --
    return this;
  }
}

new Matrix4Ext()
  .multiply(new Matrix4())
  // Error: Property 'extension' does not exist on type 'Matrix4'.
  .extension();
```

# Solution

The type definitions should be adjusted to return `this` instead of `Matrix4` if the operation is in-place and `this` is returned.
Which type definitions have to be adjusted can be inferred from the [Three.js documentation on Matrix4](https://threejs.org/docs/#api/en/math/Matrix4) (using the `this` type).

**Comment by Methuselah96** [comment]
Sure thing! Feel free to create a PR for this.
