### ISSUE TITLE
Several missing functions/props for r128

### ISSUE THREAD

**Issue by Fluqz** [three-types/three-ts-types#81]
-   `three` version: r128
-   "@types/three": "^0.92.20"

### Problem description:

I updated my project from r124 to r128, installed the three typings as stated [here](https://discourse.threejs.org/t/with-r126-typescript-type-declaration-files-are-located-at-definitelytyped/23157), but still have a few functions/properties that are missing. I dont know if the typings are missing or whether they got replaced/removed. I still find them in the docs of threejs. Found nothing about it in the changelogs

### Relevant code:

onBeforeCompile on MeshDepthMaterial

```ts
new THREE.MeshDepthMaterial().onBeforeCompile = (shader) => { } 

```

> Property ‘onBeforeCompile’ does not exist on type ‘MeshDepthMaterial’.

renderer.render(…) render mesh instead of scene

```ts
this.renderer.render( mesh, camera )

```

> Argument of type ‘Mesh’ is not assignable to parameter of type ‘Scene’.

Renderer outputencoding

```ts
renderer.outputEncoding = THREE.sRGBEncoding

```

> Property ‘outputEncoding’ does not exist on type ‘WebGLRenderer’.

WebGLMultisampleRenderTarget

```ts
new THREE.WebGLMultisampleRenderTarget()

```

> Property ‘WebGLMultisampleRenderTarget’ does not exist on type ‘typeof import("…/node_modules/@types/three/index")’.

```ts
mesh.material = [mat1, mat2, mat3, mat4, mat5, mat6]

```

> Type ‘Material[]’ is not assignable to type ‘MeshBasicMaterial | MeshDepthMaterial | MeshLambertMaterial | MeshStandardMaterial | … 5 more … | MeshMaterialType[]’.

Do I have to make every Material type MeshMaterialType now?

Any help appreciated

**Comment by joshuaellis** [comment]
If there in the docs, it's probably an issue with the typings, if you want these resolved I'd advise you to make a PR. However the `material[]` is what we're keeping. You'll have to Typecast this.

**Comment by Fluqz** [comment]
So if I dont do it, no one is going to? Nice maintenance

**Comment by joshuaellis** [comment]
Pretty much. Nice contribution to free software you're using

**Comment by Fluqz** [comment]
You took responsibility for maintaining this repo and now your complaining about people reporting bugs. Very helpful.
Im not able to fix it, I guess Im just gonna back paddle and close this issue again.

**Comment by Methuselah96** [comment]
> You took responsibility for maintaining this repo

He is maintaining it. Have you noticed that there has been a new `@types/three` version released shortly after each `three` version is released with the breaking changes from that version? That's work that someone else is putting in that you're using for free. An unmaintained repo is when the author is not responsive and won't merge PRs.

> and now your complaining about people reporting bugs. Very helpful.

There have been no complaints about people reporting bugs.

> Im not able to fix it, I guess Im just gonna back paddle and close this issue again.

Sounds like a good plan. That's your prerogative.

**Comment by Fluqz** [comment]
I didnt say that he is not maintaining the repo. But Im not able to do it and he is saying, that "pretty much" no one will do it, if I I dont do it. So I dont see any help from your side and no maintenance or fix in sight.
Its not about my prerogative, its about having no other option

**Comment by Methuselah96** [comment]
I'd be willing to look into the issues you mentioned.

Why are not able to do it yourself?

**Comment by Fluqz** [comment]
Cause I have no idea about it. I looked into the files and tried to fix it, i.e. I found the [outputEncoding](https://github.com/three-types/three-ts-types/blob/71ff599050e05afa59a06693a9d2e8bec4619cdc/types/three/src/renderers/WebGLRenderer.d.ts#L183) inside webglrenderer.d.ts. From my understanding of typings, this should already work, but its not. I already spent lots of time looking for fixes and fixing it myself, but no one is paying me either

**Comment by Methuselah96** [comment]
The version of `@types/three` that you're using is way out of date. You should be using `@types/three@^0.128.0`. I think that might clear up quite a few of your issues.

**Comment by Fluqz** [comment]
Okay interesting. Is it normal that `npm install --save @types/three` is installing a very outdated version? Anyway Im gonna try it in a minute and edit the issue accordingly

**Comment by Methuselah96** [comment]
Not that I know of. I just tried it out locally and it installed `@types/three@^0.128.0`. 👍

**Comment by Fluqz** [comment]
I dont know whats happening, but when I install the latest typings, I end up having threejs version r124 and when installing threejs r128, I end up having a very outdated typings version. I guess I uninstall both and reinstall

**Comment by joshuaellis** [comment]
I've got round to double checking these and was unable to find the issues at hand, if you can provide a codesandbox showing these issues we can reopen and rediscuss 👍🏼
