### ISSUE TITLE
Font.resolution, Font.boundingBox, Font.glyphs are missing

### ISSUE THREAD

**Issue by hybridherbst** [three-types/three-ts-types#855]
See https://github.com/mrdoob/three.js/blob/f763181aca32b483e50d418228dbc0a93dfaf61e/examples/jsm/loaders/FontLoader.js#L76
and
https://github.com/mrdoob/three.js/blob/f763181aca32b483e50d418228dbc0a93dfaf61e/examples/jsm/loaders/FontLoader.js#L107

Current workaround, probably some info missing:

```ts
declare type _Font = Omit<Font, 'data'> & { data: 
    {
        glyphs: {
            [key: string]: {
                ha: number;
            }
        },
        boundingBox: {
            xMin: number;
            xMax: number;
            yMin: number;
            yMax: number;
        }
    };
}

```

**Comment by Methuselah96** [comment]
Thanks for the issue! We [don't guarantee complete types for the examples](https://github.com/three-types/three-ts-types?tab=readme-ov-file#priorities-and-goals). Feel free to create a PR to fix this! Otherwise, I will probably get to this at some point, but not sure when yet.
