### ISSUE TITLE
Create a single three-types.d.ts file.

### ISSUE THREAD

**Issue by porterporter** [three-types/three-ts-types#859]
Hi,

I am trying to embed all of the three-ts-types src/ files into one (huge) .d.ts file. Do you know how I could edit the tsconfig.json file to bundle them all into one file?

I've tried using declaration with an outFile but when tsc succeeds it doesn't output a file.

Thanks!

**Comment by Methuselah96** [comment]
I don't have any experience doing that. TypeScript does not provide a native way to do this, but https://github.com/microsoft/TypeScript/issues/4433 presents some good ideas on how one might accomplish that with community-maintained tools, including [API Extractor](https://api-extractor.com/), [rollup-plugin-dts](https://github.com/Swatinem/rollup-plugin-dts), and [tsup](https://tsup.egoist.dev/).

Best of luck, let me know if I can help with anything else.
