### ISSUE TITLE
Can't assign global clipping planes

### ISSUE THREAD

**Issue by MarvinKubus** [three-types/three-ts-types#879]
I've been using the WebGLRenderer clippingPlanes for a while and now that I'm updating from an older version to the current version, they have been made readonly and are no longer assignable.

This example uses the renderer.clippingPlanes: https://github.com/mrdoob/three.js/blob/master/examples/webgl_clipping_advanced.html

This commit made them readonly:
https://github.com/three-types/three-ts-types/commit/c7d06ae9cbeb8800008685dba371e4311fd39824#diff-a49a68ba8d61aea7970812d8ea758823574f49c5afc1f30c47e88ab0e54ec59d

If this is intentional, then what whould be the proposed way of assigning them now, or should they not be readonly?

**Comment by Methuselah96** [comment]
They probably don't need to be `readonly`, that was probably a side-effect of the `webgl_clipping` and `webgl_clipping_advanced` examples using `Object.freeze` which produces a `readonly` array.

Note that with the current types you can still set the property (e.g., `renderer.clippingPlanes = []`), just like in the `webgl_clipping_advanced` and `webgl_clipping` examples, you just can't modify the array (e.g., `renderer.clippingPlanes.push(plane)`).

I've created https://github.com/three-types/three-ts-types/pull/880 to make them mutable in the next version of @types/three.

**Comment by MarvinKubus** [comment]
Thank you for the info and the fast PR!
It was indeed a `.push` that lead me here.
