### ISSUE TITLE
InstancedMesh geometry & material are not optional

### ISSUE THREAD

**Issue by bjornstar** [three-types/three-ts-types#92]
-   `three` version: `0.129.0`
-   `node` version: `16`
-   `npm` (or `yarn`) version: `7`

### Problem description:

geometry and material are not optional see https://github.com/pmndrs/racing-game/pull/128

### Relevant code:

```ts
    <instancedMesh ref={ref} args={[null, null, count]}>
      <boxGeometry args={[size, size, size]} />
      <meshBasicMaterial color="#5ecfff" transparent opacity={opacity} depthWrite={true} />
    </instancedMesh>
```

### Suggested solution:

geometry & material should be optional.

**Comment by joshuaellis** [comment]
Having looked into this, required parameters cannot follow optional parameters. We're therefore tied by the implementation in `three.js` where the args order is `geometry, material, count`. I will open an issue to discuss this though.

For reference of the error, see this image:
![image](https://user-images.githubusercontent.com/37798644/121803513-f628c000-cc39-11eb-8e80-1f2f465b09e8.png)

**Comment by joshuaellis** [comment]
I've opened an issue in `three.js` as you can see above

**Comment by joshuaellis** [comment]
They're not going to change it so we can't either.

**Comment by bjornstar** [comment]
I'm willing to accept the "silly" solution which is to not use `?` and allow `undefined` or `null` since they are optional.

**Comment by joshuaellis** [comment]
You can't do that unfortunately. Required parameters cannot follow optional. The types will have to stay the same unless three changes the implementation.
