### ISSUE TITLE
If() TslNode Function Not Present

### ISSUE THREAD

**Issue by cmhhelgeson** [three-types/three-ts-types#932]
If is a function that is defined within three/examples/jsm/nodes/shadernode

```export const If = ( ...params ) => currentStack.if( ...params )```

Essentially, it's goal is to construct an if statement within a tslFn function, similar to how the sub(), mul(), equals(), and Continue() Operators provide a way to construct specific mathematical statements within a tslFn. Currently, it's used within the webgpu_texturegrad.html, webgpu_storage_buffer.html, webgpu_compute_particles.hmtl, and webgpu_compute_particles_rain.html examples.

**Comment by Methuselah96** [comment]
https://github.com/three-types/three-ts-types/pull/933 should fix this. As noted before, the Nodes types are rough around the edges. Many of the examples you're looking at will still not fully type-check. I hope to get around to solidifying those types in the near to mid future.
